### ISSUE TITLE
Create storyboards

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#1]
All hands on deck! Once Krisy create a template for us, we'll all need to contribute to build out the full storyboard.

Storyboards should hit all the main interaction points - every quest pickup and turning, NPC dialogs, things we can pick up, and instruments we collect.

These should be "low-fidelity", and don't need to be a consistent style; you can scan a doodle, use Google Sheet shapes, or just type some text in boxes.

**Comment by MazurkaLFG** [comment]
Link to the Story Boards Google Slides:  https://docs.google.com/presentation/d/12_VdQMjWk85Pa-6QG7J4PmNh2YCFEjPlGNW9KtKv_jY/edit?usp=sharing

**Comment by melanie** [comment]
This is awesome!! I've added the link to the Readme on the main page, and I'm call this one closed.
