### ISSUE TITLE
Mini-game/mini-objective creation

### ISSUE THREAD

**Issue by EricDovigi** [SolidGoldStudios/SecretSymphony#19]
Here, we can put issues related to specific mini-game development.

**Comment by EricDovigi** [comment]
https://docs.google.com/document/d/1F93c2v6TiK_tcyBlt4tCYHFR-CmNQVL04g3UeHSb1G8/edit

A google doc for general mini game overview/description

**Comment by melanie** [comment]
@EricDovigi did such a great job fleshing out the minigame concepts! Woo!!
