### ISSUE TITLE
Write trivia

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#2]
We'll need trivia questions for all (8-12?) instruments. 

Trivia questions should ideally be in a spreadsheet format, with the following columns:

- Instrument
- Difficulty
- Type
- Question
- Correct Answer
- Wrong Answers 1 and 2
- Follow-up info
- World info (knowledge that you glean from a book or a conversation)

**Comment by MazurkaLFG** [comment]
Link to the spreadsheet: https://docs.google.com/spreadsheets/d/12oE4nEydaFGm_Lr3oEIAuyF05Bth0YzhIV7TN0_hzGM/edit?usp=sharing

Link to Kevin's working doc: https://docs.google.com/document/d/1f7oMRXtPZ7_0mJy61A5MGcSrqT_wkrqbtoPQvd-PHIY/edit?fbclid=IwAR0nbnbd3cd6As47Cb6ap9QeNkFapWnuu51WPvjcFM5jJWsDGajY1AmoJL4

**Comment by melanie** [comment]
I probably should have called this issue "Start trivia"! We'll probably need to reference the trivia stuff a lot as part of future issues, so I'm gonna call this one closed!
