### ISSUE TITLE
Determine "Learning" gameplay

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#20]
One big piece we're missing is the teaching aspect - have can we impart knowledge, before quizzing on it?

**Comment by EricDovigi** [comment]
Is this game designed to provide the "lesson" as well as the "quiz?" or just be a "quiz" equivalent designed to follow the teacher's own lesson?

**Comment by melanie** [comment]
Personally, I think it would have a better shot at success if it was a completely self-contained learning experience, so that players were learning from the game and the quizzes and stuff were just confirming that knowledge. But that makes it a bigger challenge!

**Comment by melanie** [comment]
I think we've pretty much covered this with books and dialog!
