### ISSUE TITLE
Portraits

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#21]
Here are the new portraits we'll need - please update the list if any are missing! Some portraits will need mood variants; check with Story Team to see what's needed.

- [x] Fairy
- [x] Chicken
- [x] Donkey
- [x] Goat(s?)
- [x] Frog Monster
- [x] Squirrel
- [x] Carriage Guy
- [x] Horse(s)
- [x] Blob Creature
- [x] Earworm

Portrait notes:
- Portraits should be 64x64px with a transparent background.
- You can cut off the left shoulder, but the right shoulder should have a natural edge. The ribbon will cover up a few pixels along the bottom.
- Make sure mood variants line up consistently - if they move over like 1px it looks jumpy

**Comment by MazurkaLFG** [comment]
Can't we just use the fairy's whole body as her portrait? Since she is tiny and we aren't using it in the real world?

**Comment by MazurkaLFG** [comment]
![spiritofmusic2](https://user-images.githubusercontent.com/66224077/101305603-a55a8980-3808-11eb-8309-7def9091b227.png)

**Comment by melanie** [comment]
Yeah, totally! I just left her un-checked because I think she'll need some mood variants, too.

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101307283-b2797780-380c-11eb-93d9-0921124fc096.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101988065-31334200-3c5d-11eb-9201-d514d3e779ef.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101988704-ea474b80-3c60-11eb-9ee2-119079043340.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101989063-75c1dc00-3c63-11eb-9ffe-e30e80a77922.png)

Okay this horse is kind of the things made of nightmares. Someone please feel free to rework this. 

Kevin's original art: 

![Uploading orchestravaganza horse.jpg…]()

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101989809-7dd04a80-3c68-11eb-9dc6-da3cebe61305.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101990846-68f6b580-3c6e-11eb-87d1-b1f2d4e09950.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101991189-ae1be700-3c70-11eb-832c-244c41c9f762.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101991211-c855c500-3c70-11eb-8bc7-7dbdc2d78c68.png)

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101994141-a0bd2780-3c85-11eb-8792-ac6adfb3e1d5.png)

**Comment by melanie** [comment]
Beautiful! Throwing 'em into Resources now!
