### ISSUE TITLE
Demolish the church

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#22]
So as to not oFfEnD sEnSiBiLiTiEs, we should remove the church and replace it with ruins.

- [x] Remove church building, replace with ruins or something else
- [x] Try to reuse assets from the church interior, if possible
- [x] Give the headstones some info about famous dead musicians

**Comment by EricDovigi** [comment]
![rubble](https://user-images.githubusercontent.com/67932984/101706370-2783c180-3a46-11eb-8921-4dfef54131bc.png)

rubble for the ruins

**Comment by EricDovigi** [comment]
![rubble_pillar](https://user-images.githubusercontent.com/67932984/101706386-2eaacf80-3a46-11eb-8150-2e968f146da6.png)

pillar

**Comment by EricDovigi** [comment]
![rubble_block](https://user-images.githubusercontent.com/67932984/101706392-32d6ed00-3a46-11eb-8bf6-c9adfd088dfa.png)
block

**Comment by EricDovigi** [comment]
![rubble_pebble2](https://user-images.githubusercontent.com/67932984/101706563-9a8d3800-3a46-11eb-8bee-c92b03f0caa4.png)

**Comment by EricDovigi** [comment]
![rubble_pebble](https://user-images.githubusercontent.com/67932984/101706566-9d882880-3a46-11eb-839a-58f1128bc7f6.png)
pebble2

**Comment by MazurkaLFG** [comment]
![image](https://user-images.githubusercontent.com/66224077/101994734-31960200-3c8a-11eb-90d7-1021d5fee4f8.png)

added shadows underneath things :)

**Comment by EricDovigi** [comment]
put some headstone text in the instrument descriptions doc

https://docs.google.com/document/d/1G22y5yYMqQBu7cA8NaYJ-vq0ZG8U0k_ugh9svMuzK5o/edit

**Comment by EricDovigi** [comment]
I tried to make it as diverse as I could, but that's not easy when it comes to classical music :*(
