### ISSUE TITLE
Fairy Scene

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#23]
The first scene in the game takes place in your room while you're sleeping. The Fairy shows up and does the whole game-start exposition. Here's what we'll need:

- [x] The Fairy's dialog
- [x] The Fairy portrait, including mood variants (see #21 )
- [x] The Fairy's in-scene sprite (see #50 )
- [ ] Put Kay in bed, disable motion controls
- [x] A scripted event that plays the fairy animation and starts dialog
- [x] A way to transition to the normal Bedroom Morning scene

**Comment by EricDovigi** [comment]
I have a short monolog for the faery in the drive. Essentially "Oh no! I can't believe everyone has forgotten about music. Help us Obi Wan Kenobi, you're our only hope."
