### ISSUE TITLE
Remove Road-to-Town scene

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#26]
Since there's no story reason to have the Road to Town scene, we should take it out. That'll tighten up the playtime, and help us to make the two main areas (Farm and Town) more densely-packed with stuff to do.

- [x] Move Carriage Guy to the farm
- [x] Re-use any assets if possible
- [x] Remove scene
- [x] Make sure Farm and Town are linked together correctly

**Comment by EricDovigi** [comment]
I think that the side-view carriage in the ToS road to town scene should be replaced with the carriages in the Town Square, since those are more top-down. But hat-man can probably stay the same
