### ISSUE TITLE
Update Bedroom scene

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#27]
- [x] Art for new room objects
- [ ] Learning points in bedroom
- [x] Add new objects in the room
- [ ] Start with the window open so it's easier to see stuff

**Comment by melanie** [comment]
Hold off on this stuff until Dustin checks in his NavMesh stuff - don't wanna get conflicts!

**Comment by EricDovigi** [comment]
![couch](https://user-images.githubusercontent.com/67932984/101678978-f2fb1000-3a1b-11eb-9ce9-09cb09f9cfad.png)
meh I don't know if this is any good, but it could fill up the space in the bottom left of the bedroom

**Comment by EricDovigi** [comment]
![couch](https://user-images.githubusercontent.com/67932984/101679143-25a50880-3a1c-11eb-81a4-b5f884391fc1.png)

**Comment by EricDovigi** [comment]
couch kinda stinks but could fit in the bottom left of the bedroom

**Comment by melanie** [comment]
I made "open window" its own `bug` issue, and I don't think we're planning to add any books to the bedroom. I'm closing this one so it doesn't hold up Week 4 completion!
