### ISSUE TITLE
Create Barn interior

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#29]
The barn will (probably?) be an explorable area, so let's flesh it out!

- [x] Update building art to remove bar over the door
- [ ] Create a new scene
- [ ] Write dialog or quests for this scene, if needed

**Comment by EricDovigi** [comment]
![barn_stable_partition](https://user-images.githubusercontent.com/67932984/101306981-97eed080-3803-11eb-8b49-89c538f5764b.png)

**Comment by EricDovigi** [comment]
stable partition (above)

**Comment by EricDovigi** [comment]
![barn_stable_wheat](https://user-images.githubusercontent.com/67932984/101307809-90302b80-3805-11eb-9fb2-0ef593a65a89.png)

some extra wheat to pepper up the barn interior

**Comment by EricDovigi** [comment]
![Barn_no_bar](https://user-images.githubusercontent.com/67932984/101543188-20cf4e80-3961-11eb-98b5-98306fbbf3ab.png)

barn without the bar
