### ISSUE TITLE
Write some info for each instrument

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#3]
Each of the 8-12 collectable instruments will need some description text. This could be long enough to fill a page in a book-style layout, or just a couple lines - that's for Story and Art to decide!

**Comment by EricDovigi** [comment]
https://docs.google.com/document/d/1G22y5yYMqQBu7cA8NaYJ-vq0ZG8U0k_ugh9svMuzK5o/edit

I thought I'd get a start on some instrument descriptions. I'm doing a short version and a long version for each. Please feel free to edit or make new descriptions.

**Comment by melanie** [comment]
@EricDovigi This looks awesome! Very readable and informative. I've copied it to Shared Drive > Secret Symphony > Docs, I hope that's okay!
https://docs.google.com/document/d/1HTKBLIKwuXNH_WlXn87RfaiyttngjunyK0-m2jrd9F0/edit?usp=sharing

Since this is pretty much all filled in, I'm gonna mark this one as closed!
