### ISSUE TITLE
Start on piano scene

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#30]
- [x] Come up with a minigame (see #19 )
- [ ] Fix that one weird direction of Kay's swipe animation
- [x] Write dialog for the scene, including Fairy tutorial

**Comment by EricDovigi** [comment]
![piano_lid_key](https://user-images.githubusercontent.com/67932984/101381030-7a594f80-3873-11eb-91cb-3920509bf5ad.png)

Piano lid key

**Comment by EricDovigi** [comment]
![piano_lid_key_inventory](https://user-images.githubusercontent.com/67932984/101381043-7e856d00-3873-11eb-8a02-0bf623e2238a.png)

Piano lid key

**Comment by EricDovigi** [comment]
![pianer-export](https://user-images.githubusercontent.com/67932984/101381567-2307af00-3874-11eb-938c-27642235c648.png)

I made the piano look better. More top-down and the angle of the legs fixed

**Comment by EricDovigi** [comment]
![pianer-closed_lidt](https://user-images.githubusercontent.com/67932984/101381759-619d6980-3874-11eb-9b32-57ef5ba5a680.png)

piano closed lid

**Comment by EricDovigi** [comment]
I put Inkies in the Discord chat. Current draft has unique knot names and fixes the "father goes outside" thing as per Krisy's request.

**Comment by MazurkaLFG** [comment]
> ![piano_lid_key_inventory](https://user-images.githubusercontent.com/67932984/101381043-7e856d00-3873-11eb-8a02-0bf623e2238a.png)
> 
> Piano lid key inventory portrait

If we're doing inventory the same way, inventory items are 16x16, so this awesome key will need to be a bit smaller, I think?

**Comment by melanie** [comment]
Consider it started - we'll deal with the wonky scythe animation someday ;)
