### ISSUE TITLE
Instrument UI concepts

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#4]
We've agreed (so far!) to have a persistent UI that shows the instruments you and haven't collected. We should mock this up in design before it goes to the Game Engine team.

**Comment by EricDovigi** [comment]
![school_blackboard](https://user-images.githubusercontent.com/67932984/100686942-95403700-333c-11eb-873a-6308fc3b4b8c.png)
![school_clock](https://user-images.githubusercontent.com/67932984/100686944-95d8cd80-333c-11eb-8d35-2f169a88862f.png)
![school_chair](https://user-images.githubusercontent.com/67932984/100686945-95d8cd80-333c-11eb-84b5-c7220614a709.png)
![school_desk](https://user-images.githubusercontent.com/67932984/100686947-95d8cd80-333c-11eb-9bcd-d51581de497d.png)

**Comment by melanie** [comment]
@EricDovigi I've saved your art in Shared Drive > Art > Furniture & Decor.

Closing this issue because it's covered in the "Cohesive UI" issue - #15
