### ISSUE TITLE
Instrument art

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#5]
Each of our instruments will need, at minimum, some pixel art for when we find them in the world. Depending on what we decide for the instrument UI (see #4  ), we might need additional versions to use there.

**Comment by MazurkaLFG** [comment]
Here's all the instruments we chose, and then a couple that we didn't choose (maybe we can use them as the after fact like.. "You're right! The bass drum IS part of the percussion family, along with instruments like maracas, triangles, and cymbals" etc.

![image](https://user-images.githubusercontent.com/66224077/100553412-6ef29c80-3253-11eb-998c-a496b302a630.png)
