### ISSUE TITLE
Determine final instrument list

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#6]
We need a final instrument list - this will be the pick-up-able instruments, and the ones that are highlighted in musical compositions.

**Comment by EricDovigi** [comment]
Flute, Oboe, Clarinet, Horn, Trombone, Tuba, Bass Drum, Marimba, Piano, Violin, Cello, Contrabass

**Comment by MazurkaLFG** [comment]
And Harp!

**Comment by MazurkaLFG** [comment]
An image using most of the instruments that we've chosen (though, thoughts on timpani instead of bass drum?)

![image](https://user-images.githubusercontent.com/66224077/100550316-bae71680-323e-11eb-8ef5-7992ac29df10.png)

**Comment by MazurkaLFG** [comment]
I think this can be closed for now... we may add in more instruments later if we get to it, but we've got a good solid start, I think!
