### ISSUE TITLE
Full symphonic score

### ISSUE THREAD

**Issue by melanie** [SolidGoldStudios/SecretSymphony#7]
This is the whole enchilada - the complete "main song" that plays when all instruments are collected.

**Comment by EricDovigi** [comment]
https://drive.google.com/drive/folders/1FuZ-yNuq8vSoZIzxunn_JdzUSwDm23m-

added the full orchestral song (current draft) to the drive, and adding the instrument jingles piecemeal. Will add the separate parts of the full song as well possibly today

**Comment by EricDovigi** [comment]
drive now includes separate instrument tracks, a single track of the whole thing, and jingles, all as .wavs. Can definitely still tweak if we decide something needs to be different.

**Comment by melanie** [comment]
Awesome - sounds like this one is done! That basically knocks out all of weeks 1 and 2 for the music team! Wow!
